from __future__ import annotations

import importlib as importlib_module
import logging as std_logging

from functions.logging.logging_utils import configure_module_logger, mask_hash

from .admin import log_admin_action
from .applications import (
    approve_application_request,
    create_application_request,
    get_application_request,
    list_application_requests,
    reject_application_request,
    _clean_optional_text,
)
from .companies import list_companies_for_invoicing
from .db import (
    TABLE_REGISTRY,
    _build_engine,
    _is_truthy,
    admin_audit_log_table,
    application_requests_table,
    companies_table,
    company_users_table,
    create_database,
    get_engine,
    password_resets_table,
    pending_supervisors_table,
    pending_users_table,
    reset_engine,
    schema_migrations_table,
    supervisor_connections_table,
    supervisor_link_requests_table,
    supervisors_table,
    user_pdfs_table,
    users_table,
)
from .demo import create_test_user, ensure_demo_data, reset_demo_database
from .constants import APP_ROOT
from .demo import DEMO_PDF_DEFINITIONS
from sqlalchemy import create_engine
from .pdf.storage import (
    delete_user_pdf,
    get_pdf_content,
    get_pdf_metadata,
    get_user_pdfs,
    store_pdf_blob,
    update_pdf_categories,
)
from .security.hashing import (
    hash_password,
    hash_value,
    normalize_email,
    normalize_orgnr,
    normalize_personnummer,
    validate_orgnr,
    verify_password,
)
from .tables import (
    create_table_row,
    delete_table_row,
    fetch_table_rows,
    get_table_schema,
    update_table_row,
)
from .users import (
    admin_create_supervisor,
    admin_create_user,
    admin_link_supervisor_to_user,
    check_password_user,
    check_pending_supervisor_hash,
    check_pending_user,
    check_pending_user_hash,
    check_personnummer_password,
    check_user_exists,
    create_password_reset_token,
    create_supervisor_link_request,
    get_password_reset,
    get_supervisor_email_hash,
    get_supervisor_login_details_for_orgnr,
    get_supervisor_name_by_hash,
    get_supervisor_overview,
    get_user_info,
    get_username,
    get_username_by_personnummer_hash,
    list_supervisor_connections,
    list_user_link_requests,
    list_user_supervisor_connections,
    reset_password_with_token,
    supervisor_activate_account,
    supervisor_exists,
    supervisor_has_access,
    supervisor_remove_connection,
    user_accept_link_request,
    user_create_user,
    user_reject_link_request,
    user_remove_supervisor_connection,
    verify_certificate,
    verify_supervisor_credentials,
)


logger = configure_module_logger(__name__)
logger.setLevel(std_logging.DEBUG)
importlib = importlib_module

__all__ = [
    "TABLE_REGISTRY",
    "_build_engine",
    "_clean_optional_text",
    "_is_truthy",
    "APP_ROOT",
    "approve_application_request",
    "admin_audit_log_table",
    "admin_create_supervisor",
    "admin_create_user",
    "admin_link_supervisor_to_user",
    "application_requests_table",
    "check_password_user",
    "check_pending_supervisor_hash",
    "check_pending_user",
    "check_pending_user_hash",
    "check_personnummer_password",
    "check_user_exists",
    "companies_table",
    "company_users_table",
    "create_application_request",
    "create_database",
    "create_engine",
    "create_password_reset_token",
    "create_supervisor_link_request",
    "create_table_row",
    "create_test_user",
    "DEMO_PDF_DEFINITIONS",
    "delete_table_row",
    "delete_user_pdf",
    "ensure_demo_data",
    "fetch_table_rows",
    "get_application_request",
    "get_engine",
    "get_password_reset",
    "get_pdf_content",
    "get_pdf_metadata",
    "get_supervisor_email_hash",
    "get_supervisor_login_details_for_orgnr",
    "get_supervisor_name_by_hash",
    "get_supervisor_overview",
    "get_table_schema",
    "get_user_info",
    "get_user_pdfs",
    "get_username",
    "get_username_by_personnummer_hash",
    "hash_password",
    "hash_value",
    "list_application_requests",
    "list_companies_for_invoicing",
    "list_supervisor_connections",
    "list_user_link_requests",
    "list_user_supervisor_connections",
    "log_admin_action",
    "logger",
    "importlib",
    "mask_hash",
    "normalize_email",
    "normalize_orgnr",
    "normalize_personnummer",
    "password_resets_table",
    "pending_supervisors_table",
    "pending_users_table",
    "reject_application_request",
    "reset_demo_database",
    "reset_engine",
    "reset_password_with_token",
    "schema_migrations_table",
    "store_pdf_blob",
    "supervisor_activate_account",
    "supervisor_connections_table",
    "supervisor_exists",
    "supervisor_has_access",
    "supervisor_link_requests_table",
    "supervisor_remove_connection",
    "supervisors_table",
    "update_pdf_categories",
    "update_table_row",
    "user_pdfs_table",
    "user_accept_link_request",
    "user_create_user",
    "user_reject_link_request",
    "user_remove_supervisor_connection",
    "users_table",
    "validate_orgnr",
    "verify_certificate",
    "verify_password",
    "verify_supervisor_credentials",
]
