name: Stavningskontroll (svenska)

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  cspell:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache cspell
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/cspell
            **/node_modules
          key: cspell-${{ runner.os }}-${{ hashFiles('.cspell.json', 'cspell-words.txt') }}

      - name: Install cspell + svensk ordbok
        run: |
          npm install -g cspell cspell-dict-sv

      # Kör stavningskontroll på vanliga text- och kodfiler
      - name: Run cspell
        run: |
          cspell \
            "**/*.{md,txt,html,css,scss,json,yml,yaml,ts,tsx,js,jsx,py,java,cs,cpp,c,h,rs,go,rb,php,kt,swift}" \
            --no-progress \
            --config .cspell.json

      # Visa tydligare fel i Actions-loggen vid PR
      - name: Fail if issues found
        if: ${{ failure() }}
        run: |
          echo "Stavfel hittades. Se loggen ovan för detaljer."
          exit 1
